return {
	{
		-- Theme inspired by Atom
		"navarasu/onedark.nvim",
		priority = 1000,
	},
	{ dir = "~/projects/dracula_pro", priority = 1000, lazy = false },
	{
		"catppuccin/nvim",
		priority = 1000,
		name = "catppuccin",
		opts = {
			integrations = {
				aerial = true,
				alpha = true,
				cmp = true,
				dashboard = true,
				flash = true,
				gitsigns = true,
				headlines = true,
				illuminate = true,
				indent_blankline = { enabled = true },
				leap = true,
				lsp_trouble = true,
				mason = true,
				markdown = true,
				mini = true,
				native_lsp = {
					enabled = true,
					underlines = {
						errors = { "undercurl" },
						hints = { "undercurl" },
						warnings = { "undercurl" },
						information = { "undercurl" },
					},
				},
				navic = { enabled = true, custom_bg = "lualine" },
				neotest = true,
				neotree = true,
				noice = true,
				notify = true,
				semantic_tokens = true,
				telescope = true,
				treesitter = true,
				treesitter_context = true,
				which_key = true,
			},
		},
		config = {
			color_overrides = {
				mocha = {
					rosewater = "#f5e0dc",
					pink = "#f5c2e7",
					-- mauve = "#cba6f7",
					maroon = "#eba0ac",
					teal = "#94e2d5",
					sapphire = "#74c7ec",
					subtext1 = "#bac2de",
					subtext0 = "#a6adc8",
					overlay2 = "#9399b2",
					overlay1 = "#7f849c",
					overlay0 = "#6c7086",
					surface2 = "#585b70",
					surface1 = "#45475a",
					surface0 = "#313244",
					--
					mantle = "#181825",
					crust = "#11111b",
					bg = "#0b0d0f",
					base = "#0b0d0f",
					fg = "#FFFFFF",
					text = "#FFFFFF",
					blue = "#006AFF",
					green = "#04D000",
					lavender = "#6400FF",
					red = "#C10B1E",
					yellow = "#F6F332",
					flamingo = "#DF8B01",
					sky = "#80FFEA",
					peach = "#DF8B01",
					mauve = "#FF114F",
				},
			},
		}
	},
	{ "lunarvim/lunar.nvim" },
	{
		"Mofiqul/vscode.nvim",
	},
	{ "bluz71/vim-nightfly-colors", name = "nightfly", lazy = false, priority = 1000 },
	{
		"folke/tokyonight.nvim",
		lazy = false,
		priority = 1000,
		opts = {},
	},
	{ "shaunsingh/moonlight.nvim" },
	{ "rose-pine/neovim", name = "rose-pine", priority = 1000 },
	{ "miikanissi/modus-themes.nvim", priority = 1000 },
	{ "oxfist/night-owl.nvim", priority = 1000 },
}
